import {describe, it, expect} from 'vitest';
import {Descriptor, LocatorHash, Package} from '@yarnpkg/core';
import {generateProdLockfile, generateDockerPackageJson} from '../sources/lockfile.js';
import {CollectedPackage} from '../sources/traversal.js';
import {ppath, xfs} from '@yarnpkg/fslib';

describe('generateProdLockfile', () => {
  it('generates lockfile with correct workspace package keys and versions', async () => {
    const mockProject = {
      tryWorkspaceByLocator: () => null,
      storedPackages: new Map(),
      storedResolutions: new Map([
        ['common-desc', 'common-hash' as LocatorHash],
      ]),
    } as any;

    const apiHash = 'api-hash' as LocatorHash;
    const commonHash = 'common-hash' as LocatorHash;

    const apiPkg = {
      scope: 'my-org',
      name: 'api',
      identHash: 'api',
      reference: 'workspace:components/api',
      version: '1.0.0',
      dependencies: new Map([
        ['@my-org/common', {
          scope: 'my-org',
          name: 'common',
          identHash: 'common',
          descriptorHash: 'common-desc' as any,
          range: '^1.0.0',
        } as Descriptor],
      ]),
    } as unknown as Package;

    const commonPkg = {
      scope: 'my-org',
      name: 'common',
      identHash: 'common',
      reference: 'npm:1.0.0',
      version: '1.0.0',
      dependencies: new Map(),
    } as unknown as Package;

    const collected = new Map<LocatorHash, CollectedPackage>([
      [apiHash, {
        locatorHash: apiHash,
        pkg: apiPkg,
        isWorkspace: true,
        descriptors: new Set([
          {
            identHash: 'api',
            descriptorHash: 'api-desc' as any,
            range: '^1.0.0',
          } as Descriptor,
        ]),
      }],
      [commonHash, {
        locatorHash: commonHash,
        pkg: commonPkg,
        isWorkspace: true,
        descriptors: new Set([
          {
            identHash: 'common',
            descriptorHash: 'common-desc' as any,
            range: '^1.0.0',
          } as Descriptor,
        ]),
      }],
    ]);

    const outputPath = ppath.resolve('/tmp/test.yarn.lock' as any);
    await generateProdLockfile(mockProject, collected, outputPath, '@my-org/api', '1.0.0', undefined);

    const content = await xfs.readFilePromise(outputPath, 'utf8');

    expect(content).toContain('# This file is generated by running "yarn install"');
    expect(content).not.toContain('workspace:.');
    expect(content).toContain('"@my-org/api@npm:1.0.0":');
    expect(content).toContain('"@my-org/common@npm:1.0.0":');
    expect(content).toContain('version: 1.0.0');
    expect(content).toContain('"@my-org/common": "npm:1.0.0"');

    const hardLinkCount = (content.match(/linkType: hard/g) || []).length;
    expect(hardLinkCount).toBeGreaterThan(0);

    await xfs.unlinkPromise(outputPath);
  });

  it('uses correct dependency ranges for workspace packages', async () => {
    const mockProject = {
      tryWorkspaceByLocator: () => null,
      storedPackages: new Map(),
      storedResolutions: new Map([
        ['dep-desc', 'dep-hash' as LocatorHash],
      ]),
    } as any;

    const pkgHash = 'pkg-hash' as LocatorHash;
    const depHash = 'dep-hash' as LocatorHash;

    const pkg = {
      scope: 'my-org',
      name: 'pkg',
      identHash: 'pkg',
      version: '1.0.0',
      dependencies: new Map([
        ['@my-org/dep', {
          scope: 'my-org',
          name: 'dep',
          identHash: 'dep',
          descriptorHash: 'dep-desc' as any,
          range: '^1.0.0',
        } as Descriptor],
      ]),
    } as unknown as Package;

    const dep = {
      scope: 'my-org',
      name: 'dep',
      identHash: 'dep',
      version: '1.0.0',
      dependencies: new Map(),
    } as unknown as Package;

    const collected = new Map<LocatorHash, CollectedPackage>([
      [pkgHash, {
        locatorHash: pkgHash,
        pkg,
        isWorkspace: true,
        descriptors: new Set([{
          identHash: 'pkg',
          descriptorHash: 'pkg-desc' as any,
          range: '^1.0.0',
        } as Descriptor]),
      }],
      [depHash, {
        locatorHash: depHash,
        pkg: dep,
        isWorkspace: true,
        descriptors: new Set([{
          identHash: 'dep',
          descriptorHash: 'dep-desc' as any,
          range: '^1.0.0',
        } as Descriptor]),
      }],
    ]);

    const outputPath = ppath.resolve('/tmp/test2.yarn.lock' as any);
    await generateProdLockfile(mockProject, collected, outputPath, '@my-org/pkg', '1.0.0', undefined);

    const content = await xfs.readFilePromise(outputPath, 'utf8');

    expect(content).toContain('"@my-org/dep": "npm:1.0.0"');

    await xfs.unlinkPromise(outputPath);
  });

  it('includes both workspace and npm dependencies', async () => {
    const mockProject = {
      tryWorkspaceByLocator: () => null,
      storedPackages: new Map(),
      storedResolutions: new Map([
        ['express-desc', 'dep1-hash' as LocatorHash],
        ['common-desc', 'dep2-hash' as LocatorHash],
      ]),
    } as any;

    const pkgHash = 'pkg-hash' as LocatorHash;
    const dep1Hash = 'dep1-hash' as LocatorHash;
    const dep2Hash = 'dep2-hash' as LocatorHash;

    const pkg = {
      scope: 'my-org',
      name: 'pkg',
      identHash: 'pkg',
      version: '1.0.0',
      dependencies: new Map([
        ['express', {
          scope: null,
          name: 'express',
          identHash: 'express',
          descriptorHash: 'express-desc' as any,
          range: '^5.0.0',
        } as Descriptor],
        ['@my-org/common', {
          scope: 'my-org',
          name: 'common',
          identHash: 'common',
          descriptorHash: 'common-desc' as any,
          range: '^1.0.0',
        } as Descriptor],
      ]),
    } as unknown as Package;

    const express = {
      scope: null,
      name: 'express',
      identHash: 'express',
      version: '5.2.1',
      dependencies: new Map(),
    } as unknown as Package;

    const common = {
      scope: 'my-org',
      name: 'common',
      identHash: 'common',
      version: '1.0.0',
      dependencies: new Map(),
    } as unknown as Package;

    const collected = new Map<LocatorHash, CollectedPackage>([
      [pkgHash, {
        locatorHash: pkgHash,
        pkg,
        isWorkspace: true,
        descriptors: new Set([{
          identHash: 'pkg',
          descriptorHash: 'pkg-desc' as any,
          range: '^1.0.0',
        } as Descriptor]),
      }],
      [dep1Hash, {
        locatorHash: dep1Hash,
        pkg: express,
        isWorkspace: false,
        descriptors: new Set([{
          identHash: 'express',
          descriptorHash: 'express-desc' as any,
          range: '^5.0.0',
        } as Descriptor]),
      }],
      [dep2Hash, {
        locatorHash: dep2Hash,
        pkg: common,
        isWorkspace: true,
        descriptors: new Set([{
          identHash: 'common',
          descriptorHash: 'common-desc' as any,
          range: '^1.0.0',
        } as Descriptor]),
      }],
    ]);

    const outputPath = ppath.resolve('/tmp/test3.yarn.lock' as any);
    await generateProdLockfile(mockProject, collected, outputPath, '@my-org/pkg', '1.0.0', undefined);

    const content = await xfs.readFilePromise(outputPath, 'utf8');

    expect(content).toContain('express: ^5.0.0');
    expect(content).toContain('"@my-org/common": "npm:1.0.0"');
    expect(content).toMatch(/express@.*5\.2\.1/);

    await xfs.unlinkPromise(outputPath);
  });

  it('custom workspaceVersion is used for keys, versions, and dependency references', async () => {
    const mockProject = {
      tryWorkspaceByLocator: () => null,
      storedPackages: new Map(),
      storedResolutions: new Map([
        ['dep-desc', 'dep-hash' as LocatorHash],
      ]),
    } as any;

    const pkgHash = 'pkg-hash' as LocatorHash;
    const depHash = 'dep-hash' as LocatorHash;

    const pkg = {
      scope: 'my-org',
      name: 'api',
      identHash: 'api',
      version: '1.0.0',
      dependencies: new Map([
        ['@my-org/common', {
          scope: 'my-org',
          name: 'common',
          identHash: 'common',
          descriptorHash: 'dep-desc' as any,
          range: 'npm:^1.0.0',
        } as Descriptor],
      ]),
    } as unknown as Package;

    const dep = {
      scope: 'my-org',
      name: 'common',
      identHash: 'common',
      version: '1.0.0',
      dependencies: new Map(),
    } as unknown as Package;

    const collected = new Map<LocatorHash, CollectedPackage>([
      [pkgHash, {locatorHash: pkgHash, pkg, isWorkspace: true, descriptors: new Set()}],
      [depHash, {locatorHash: depHash, pkg: dep, isWorkspace: true, descriptors: new Set()}],
    ]);

    const outputPath = ppath.resolve('/tmp/test4.yarn.lock' as any);
    await generateProdLockfile(mockProject, collected, outputPath, '@my-org/api', '2.3.4', undefined);

    const content = await xfs.readFilePromise(outputPath, 'utf8');

    expect(content).toContain('"@my-org/api@npm:2.3.4":');
    expect(content).toContain('"@my-org/common@npm:2.3.4":');
    expect(content).toContain('version: 2.3.4');
    expect(content).toContain('"@my-org/common": "npm:2.3.4"');

    await xfs.unlinkPromise(outputPath);
  });

  it('wrap mode: adds wrapper root entry with focused workspace as dependency', async () => {
    const mockProject = {
      tryWorkspaceByLocator: () => null,
      storedPackages: new Map(),
      storedResolutions: new Map(),
    } as any;

    const apiHash = 'api-hash' as LocatorHash;
    const apiPkg = {
      scope: 'my-org',
      name: 'api',
      identHash: 'api',
      version: '1.0.0',
      dependencies: new Map(),
    } as unknown as Package;

    const collected = new Map<LocatorHash, CollectedPackage>([
      [apiHash, {locatorHash: apiHash, pkg: apiPkg, isWorkspace: true, descriptors: new Set()}],
    ]);

    const outputPath = ppath.resolve('/tmp/test-wrap.yarn.lock' as any);
    await generateProdLockfile(mockProject, collected, outputPath, '@my-org/api', '1.0.0', '@my-org/api-run');

    const content = await xfs.readFilePromise(outputPath, 'utf8');

    expect(content).toContain('@my-org/api-run@workspace:.');
    expect(content).toContain('"@my-org/api": "npm:1.0.0"');
    expect(content).toContain('"@my-org/api@npm:1.0.0":');

    await xfs.unlinkPromise(outputPath);
  });
});

describe('generateDockerPackageJson', () => {
  it('generates package.json with focused workspace name and its production deps', async () => {
    const outputPath = ppath.resolve('/tmp/test-nowrap.package.json' as any);
    await generateDockerPackageJson(outputPath, '@my-org/api', {'express': '^5.0.0'}, '1.0.0', undefined);

    const content = JSON.parse(await xfs.readFilePromise(outputPath, 'utf8'));
    expect(content.name).toBe('@my-org/api');
    expect(content.dependencies).toEqual({'express': '^5.0.0'});

    await xfs.unlinkPromise(outputPath);
  });

  it('wrap mode: generates wrapper package.json with focused workspace as dependency', async () => {
    const outputPath = ppath.resolve('/tmp/test-wrap.package.json' as any);
    await generateDockerPackageJson(outputPath, '@my-org/api', {}, '1.0.0', '@my-org/api-run');

    const content = JSON.parse(await xfs.readFilePromise(outputPath, 'utf8'));
    expect(content.name).toBe('@my-org/api-run');
    expect(content.dependencies).toEqual({'@my-org/api': 'npm:1.0.0'});

    await xfs.unlinkPromise(outputPath);
  });
});
