import { Project, Package, structUtils, LocatorHash, Descriptor } from "@yarnpkg/core";
import { xfs, PortablePath } from "@yarnpkg/fslib";
import { stringifySyml } from "@yarnpkg/parsers";

import { CollectedPackage, resolvePhysicalLocator } from "./traversal";

interface LockfileEntry {
  version: string;
  resolution: string;
  dependencies?: Record<string, string>;
  checksum?: string;
  languageName: string;
  linkType: string;
}

/**
 * Generate a production-only yarn.lock from collected packages.
 */
export async function generateProdLockfile(
  project: Project,
  collected: Map<LocatorHash, CollectedPackage>,
  outputPath: PortablePath,
  focusedWorkspaceName: string,
  workspaceVersion: string,
  wrapPackageName: string | undefined,
): Promise<void> {
  const entries: Record<string, LockfileEntry> = {};

  if (wrapPackageName) {
    const rootKey = `${wrapPackageName}@workspace:.`;
    entries[rootKey] = buildRootPackageEntry(wrapPackageName, focusedWorkspaceName, workspaceVersion);
  }

  for (const { pkg, isWorkspace, descriptors } of collected.values()) {
    const key = buildLockfileKey(pkg, isWorkspace, descriptors, workspaceVersion);
    const entry = buildLockfileEntry(project, pkg, collected, isWorkspace, workspaceVersion);
    entries[key] = entry;
  }

  const lockfileContent = serializeLockfile(entries);
  await xfs.writeFilePromise(outputPath, lockfileContent);
}

function buildRootPackageEntry(rootPackageName: string, focusedWorkspaceName: string, workspaceVersion: string): LockfileEntry {
  return {
    version: "0.0.0-use.local",
    resolution: `${rootPackageName}@workspace:.`,
    dependencies: {
      [focusedWorkspaceName]: `npm:${workspaceVersion}`,
    },
    languageName: "unknown",
    linkType: "soft",
  };
}

function buildLockfileKey(pkg: Package, isWorkspace: boolean, descriptors: Set<Descriptor>, workspaceVersion: string): string {
  const name = structUtils.stringifyIdent(pkg);

  if (isWorkspace) {
    return `${name}@npm:${workspaceVersion}`;
  }

  if (descriptors.size > 0) {
    const descriptorStrings = Array.from(descriptors).map((d) => structUtils.stringifyDescriptor(d));
    const uniqueDescriptors = Array.from(new Set(descriptorStrings)).sort();
    return uniqueDescriptors.join(", ");
  }

  const reference = pkg.reference;
  return `${name}@${reference}`;
}

function buildLockfileEntry(
  project: Project,
  pkg: Package,
  collected: Map<LocatorHash, CollectedPackage>,
  isWorkspace: boolean,
  workspaceVersion: string,
): LockfileEntry {
  const name = structUtils.stringifyIdent(pkg);

  const version = isWorkspace ? workspaceVersion : (pkg.version ?? "0.0.0");
  const resolution = `${name}@npm:${version}`;

  const entry: LockfileEntry = {
    version,
    resolution,
    languageName: "node",
    // All packages in Docker are hard links (fetched from registry)
    linkType: "hard",
  };

  const dependencies = pkg.dependencies;

  if (dependencies.size > 0) {
    const deps: Record<string, string> = {};

    for (const descriptor of dependencies.values()) {
      const resolution = resolvePhysicalLocator(project, descriptor.descriptorHash);
      if (!resolution || !collected.has(resolution)) {
        continue;
      }

      const baseDescriptor = structUtils.isVirtualDescriptor(descriptor)
        ? structUtils.devirtualizeDescriptor(descriptor)
        : descriptor;

      const depName = structUtils.stringifyIdent(baseDescriptor);
      const depCollected = collected.get(resolution);

      if (depCollected) {
        if (depCollected.isWorkspace) {
          deps[depName] = `npm:${workspaceVersion}`;
        } else {
          deps[depName] = baseDescriptor.range;
        }
      }
    }

    if (Object.keys(deps).length > 0) {
      entry.dependencies = deps;
    }
  }

  return entry;
}

export async function generateDockerPackageJson(
  outputPath: PortablePath,
  focusedWorkspaceName: string,
  focusedWorkspaceDependencies: Record<string, string>,
  workspaceVersion: string,
  wrapPackageName: string | undefined,
): Promise<void> {
  const packageJson = wrapPackageName
    ? {
        name: wrapPackageName,
        dependencies: {
          [focusedWorkspaceName]: `npm:${workspaceVersion}`,
        },
      }
    : {
        name: focusedWorkspaceName,
        dependencies: focusedWorkspaceDependencies,
      };

  await xfs.writeFilePromise(outputPath, JSON.stringify(packageJson, null, 2) + "\n");
}

function serializeLockfile(entries: Record<string, LockfileEntry>): string {
  const lockfileData = {
    __metadata: {
      version: 8,
      cacheKey: "10c0",
    },
    ...entries,
  };

  const header =
    '# This file is generated by running "yarn install" inside your project.\n' +
    "# Manual changes might be lost - proceed with caution!\n\n";

  return header + stringifySyml(lockfileData);
}
